
project_id = "obmrbvozmozvvxirrils"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

[functions.generate-post]
verify_jwt = true

[functions.scrapeURL]
verify_jwt = true

[functions.demoGenerate]
verify_jwt = false

[functions.checkQuota]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.linkedin-profile-sync]
verify_jwt = true

[functions.post-to-linkedin]
verify_jwt = true

[functions.linkedin-oauth-connect]
verify_jwt = true
