import { motion } from "framer-motion";

export const HeroSamplePost = () => (
  <motion.div
    initial={{ opacity: 0, y: 40 }}
    animate={{ opacity: 1, y: 0 }}
    whileHover={{
      scale: 1.02,
      transition: {
        type: "spring",
        stiffness: 400,
        damping: 25,
      },
    }}
    transition={{ duration: 1, delay: 1, ease: "easeOut" }}
    className="
      relative
      max-w-[600px] w-full
      p-8
      rounded-2xl
      bg-white/90 backdrop-blur-md
      flex flex-col justify-between
      mx-auto
      mb-16
      cursor-pointer
      transform-gpu
      will-change-transform
      shadow-xl
    "
    style={{
      background: "linear-gradient(120deg, rgba(255,255,255,0.96), rgba(220,255,255,0.2))",
      boxShadow: "0 8px 32px rgba(80, 200, 255, 0.12), 0 1px 6px rgba(0, 0, 0, 0.04)",
    }}
    aria-label="Example LinkedIn post generated by PostArc"
  >
    {/* Score badge */}
    <div className="flex items-center gap-2 text-sm font-medium mb-2 text-[#0B1C34]">
      <span className="bg-[#E6FFFB] text-[#0B1C34] px-2 py-1 rounded-full text-xs font-semibold">
        ✅ Quality Score: 94%
      </span>
    </div>

    {/* Post content */}
    <div className="flex flex-col gap-4 text-left">
      <h2 className="font-poppins font-semibold text-[20px] leading-snug text-[#0B1C34]">
        🚀 The Future of Content Creation: AI-Powered LinkedIn Success
      </h2>
      <div className="space-y-3 text-[15px] leading-[1.7] text-[#0B1C34] font-inter">
        <p>
          After 6 months of experimenting with AI-powered content creation, I've discovered a game-changing approach that’s transformed my LinkedIn presence. The results? 3x engagement and 2x connection requests.
        </p>
        <p>
          The key insight: AI isn't just about automation—it's about amplifying your authentic voice. By combining AI tools with personal insights, we can create content that resonates deeply while maintaining our unique perspective.
        </p>
        <p>
          What’s your experience with AI in content creation? Share your thoughts below 👇
        </p>
        <p className="text-[#65758C]">
          #AI #ContentCreation #LinkedInGrowth #DigitalTransformation
        </p>
      </div>
    </div>

    {/* Footer section */}
    <div className="flex items-center justify-between text-[#65758C] text-[13px] font-inter mt-6 pt-4 border-t border-slate-100/60">
      <div className="flex items-center gap-5">
        <span className="flex items-center gap-1.5">❤️ <span className="font-semibold text-[#0B1C34]">1,982</span></span>
        <span className="flex items-center gap-1.5">💬 <span className="font-semibold text-[#0B1C34]">134</span></span>
        <span className="flex items-center gap-1.5">👁️ <span className="font-semibold text-[#0B1C34]">12.4K views</span></span>
      </div>
      <span className="text-[#00FFC2] text-xs font-semibold tracking-wide">
        ✨ Generated by PostArc
      </span>
    </div>

    {/* Subtle background effect */}
    <div
      className="absolute inset-0 rounded-2xl opacity-5 pointer-events-none"
      style={{
        background: "radial-gradient(circle at top right, rgba(0,255,194,0.2), rgba(180,120,255,0.08))",
      }}
    />
  </motion.div>
);
