
import { PostsCreatedCounter } from './postShowcase/PostsCreatedCounter';
import { PostsGrid } from './postShowcase/PostsGrid';
import { ActivityTicker } from './postShowcase/ActivityTicker';
import { PostShowcaseCTA } from './postShowcase/PostShowcaseCTA';
import { usePostShowcaseState } from './postShowcase/hooks/usePostShowcaseState';

interface PostShowcaseProps {
  onTryNowClick?: () => void;
}

export const PostShowcase = ({ onTryNowClick }: PostShowcaseProps) => {
  const { currentActivity, postsCreated } = usePostShowcaseState();

  return (
    <section className="py-20 relative bg-gradient-to-b from-slate-50 via-white to-slate-50">
      {/* Subtle Background Effects */}
      <div className="absolute inset-0 opacity-[0.02]">
        <div className="absolute top-10 left-10 w-72 h-72 bg-blue-400 rounded-full blur-3xl"></div>
        <div className="absolute bottom-10 right-10 w-96 h-96 bg-purple-400 rounded-full blur-3xl"></div>
      </div>
      
      <div className="container mx-auto px-6 relative">
        <PostsCreatedCounter postsCreated={postsCreated} />

        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-heading font-bold text-midnight mb-8">
            Real Posts, Real Results
          </h2>
          <p className="text-xl text-slate max-w-2xl mx-auto">
            See the actual LinkedIn posts generated by AI and shared by industry leaders
          </p>
        </div>

        <PostsGrid />

        <ActivityTicker currentActivity={currentActivity} />

        <PostShowcaseCTA onTryNowClick={onTryNowClick} />
      </div>
    </section>
  );
};
