// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obmrbvozmozvvxirrils.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibXJidm96bW96dnZ4aXJyaWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDUyNzAsImV4cCI6MjA2NDcyMTI3MH0.uDB-DyqXACeD8CwT_6AJ0o5Tyj61xz6-F0J-JfR_bu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);